export type {
	ApplyRatioOptions,
	ApplyRatioParams,
	AutoBearTrapFormationOptions,
	AutoBearTrapFormationParams,
	ClampTroopValueOptions,
	ClampTroopValueParams,
	CustomRatio,
	TroopAssistantCalculationResult,
	TroopAssistantContext,
	TroopAssistantState,
	TroopBuff,
	TroopCapacity,
	TroopCounts,
	TroopFormation,
	TroopFormationResult,
	TroopLegion,
	TroopPreset,
	TroopRatio,
	TroopRatioCalculation,
	TroopRatioTuple,
	TroopRemaining,
	TroopTotals,
	TroopType,
} from "../type";
export {
	applyRatioToLegion,
	autoBearTrapFormation,
	calculateTroopDistribution,
	clampTroopValue,
	createLegion,
	distributeAllLegions,
	legionTotal,
	remainingGlobal,
	remainingLegionCapacity,
	totalUsed,
} from "../utils/TroopAssistantUtils";
export {
	calculateBearTrapFormation,
	calculateFormation,
	calculateFormationBuff,
	calculateFormationLegions,
	calculateFormationSummary,
	calculateMaxJoinerCapacity,
	createFormationOptions,
	mergeFormationResults,
	normalizeJoinerSize,
	TUMBLING_VALUES,
	URSA_BANE_VALUES,
} from "./calculateFormation";
export {
	calculatePreferredRatio,
	calculateRawRatio,
	calculateRemainingTroops,
	calculateSuggestedRatio,
	calculateTroopRatios,
	calculateUnlockedCapacity,
	simulateTroopDistribution,
} from "./calculateRatio";

export type {
	CalculatePreferredRatioOptions,
	CalculateRemainingTroopsOptions,
	CalculateSuggestedRatioOptions,
	CalculateTroopAssistantOptions,
	CalculateTroopTotalsOptions,
	CalculateUnlockedCapacityOptions,
	RatioResult,
	RemainingTroopsResult,
	SimulateTroopDistributionOptions,
	TroopDistributionSimulation,
	TroopTotalsResult,
	UnlockedCapacityResult,
} from "./types";
